version: '3.7'

services:
  redis:
    container_name: qrcode_expiration_redis
    image: redis
    command: [ "--notify-keyspace-events", "Ex" ]
    ports:
      - 6379:6379
    networks:
      - enviroment

  mongo:
    image: mongo
    container_name: qrcode_expiration_mongodb
    ports:
      - "27018:27017"
    networks:
      - enviroment

networks:
  enviroment:
